### ISSUE TITLE
Typo in index.json for Swift Microservice

### ISSUE THREAD

**Issue by jgwest** [kabanero-io/codewind-templates#5]
The `microcservice` typo was previously fixed in the `meta.yaml`  (https://github.com/kabanero-io/codewind-templates/commit/ab5f4b81d0b5cc565f48b775dfe93db4382bc84e), but still exists in `index.json`  (https://github.com/kabanero-io/codewind-templates/blob/master/devfiles/index.json)

```
,{
  "displayName":"Swift microcservice template", <-----
  "description":"Template for building a Swift microservice",
  "language":"swift",
  "projectType":"swift",
  "location":"https://github.com/microclimate-dev2ops/swiftTemplate",
  "links": {"self":"/devfiles/swiftTemplate/devfile.yaml" }
}
```

@tobespc

**Comment by makandre** [comment]
Seems this got fixed already, not a microcservice in sight... https://github.com/kabanero-io/codewind-templates/blob/master/devfiles/index.json#L35
